# Generated by Django 2.1.5 on 2022-11-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_factura', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('numero_referencia', models.IntegerField()),
                ('numero_comprobante', models.IntegerField()),
                ('valor_pagado', models.FloatField()),
                ('num_cuenta', models.IntegerField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Documento')),
            ],
        ),
    ]
