# Generated by Django 3.2.6 on 2022-10-22 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('lenghX', models.FloatField()),
                ('lenghY', models.FloatField()),
                ('campo', models.CharField(max_length=50)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formato.formato')),
            ],
        ),
    ]
