# Generated by Django 3.2.6 on 2022-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('cuotas', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
